//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeatrEntities : DbContext
    {
        private static TeatrEntities _context;
        public static TeatrEntities GetContext()
        {
            if (_context == null)
                _context = new TeatrEntities();

            return _context;
        }
        public TeatrEntities()
            : base("name=TeatrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Работники_театра> Работники_театра { get; set; }
        public virtual DbSet<Расписание_гастролей> Расписание_гастролей { get; set; }
        public virtual DbSet<Репертуар_театра> Репертуар_театра { get; set; }
        public virtual DbSet<Спектакли> Спектакли { get; set; }
        public virtual DbSet<Труппа_спектакля> Труппа_спектакля { get; set; }
        public virtual DbSet<RabothikSmall> RabothikSmall { get; set; }
    }
}
