//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание_гастролей
    {
        public int РасписаниеID { get; set; }
        public string Название { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public System.DateTime Дата_окончания { get; set; }
        public string Места_проведения { get; set; }
        public int СпектакльID { get; set; }
    
        public virtual Спектакли Спектакли { get; set; }
    }
}
