//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Репертуар_театра
    {
        public int РепертуарID { get; set; }
        public int СпектакльID { get; set; }
        public DateTime Дата_премьеры { get; set; }
        public string Период_проведения { get; set; }
        public string Дни_и_время { get; set; }
        public decimal Цена_билета { get; set; }
    
        public virtual Спектакли Спектакли { get; set; }
        // Дополнительное свойство только с датой
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public DateTime Дата_премьеры_ТолькоДата
        {
            get { return Дата_премьеры.Date; }
        }
    }
}
