//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Спектакли
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Спектакли()
        {
            this.Расписание_гастролей = new HashSet<Расписание_гастролей>();
            this.Репертуар_театра = new HashSet<Репертуар_театра>();
            this.Труппа_спектакля = new HashSet<Труппа_спектакля>();
        }
    
        public int СпектакльID { get; set; }
        public string Название { get; set; }
        public Nullable<int> Режиссер_постановщик { get; set; }
        public Nullable<int> Художник_постановщик { get; set; }
        public Nullable<int> Дирижер_постановщик { get; set; }
        public string Автор { get; set; }
        public string Жанр { get; set; }
        public string Тип { get; set; }
        public string Фото { get; set; }
    
        public virtual Работники_театра Работники_театра { get; set; }
        public virtual Работники_театра Работники_театра1 { get; set; }
        public virtual Работники_театра Работники_театра2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание_гастролей> Расписание_гастролей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Репертуар_театра> Репертуар_театра { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Труппа_спектакля> Труппа_спектакля { get; set; }
    }
}
