//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Труппа_спектакля
    {
        public int ID { get; set; }
        public int ТруппаID { get; set; }
        public int СпектакльID { get; set; }
        public int АктёрID { get; set; }
        public string Название_роли { get; set; }
    
        public virtual Работники_театра Работники_театра { get; set; }
        public virtual Спектакли Спектакли { get; set; }
    }
}
